// Generated by CoffeeScript 1.3.3
(function() {
  var CreditCard;

  CreditCard = (function() {

    function CreditCard() {}

    CreditCard.types = {
      visa: /^4[0-9]{12}([0-9]{3})?$/,
      mastercard: /^5[1-5][0-9]{14}$/,
      amex: /^3[4|7][0-9]{13}$/,
      discover: /^(?:6011|644[0-9]|65[0-9]{2})[0-9]{12}$/
    };

    CreditCard.type = function(number) {
      var regex, type, _ref;
      _ref = this.types;
      for (type in _ref) {
        regex = _ref[type];
        if (regex.test(number)) {
          return type;
        }
      }
      return false;
    };

    CreditCard.luhn = function(number) {
      var digit, odd, sum, _i, _len, _ref;
      sum = 0;
      odd = true;
      _ref = number.split('').reverse();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        digit = _ref[_i];
        digit = parseInt(digit);
        if ((odd = !odd)) {
          digit *= 2;
          if (digit > 9) {
            digit -= 9;
          }
        }
        sum += digit;
      }
      return sum % 10 === 0;
    };

    CreditCard.valid = function(number) {
      return this.type(number) !== false && this.luhn(number);
    };

    return CreditCard;

  })();

  this.CreditCard = CreditCard;

}).call(this);
